api/urls.py
from django.urls import path

from api.views import BookReviewDetailAPIView, BookReviewAPIView

app_name = 'api'
urlpatterns = [
    path("reviews/", BookReviewAPIView.as_view(), name='review-list'),
    path("reviews/<int:id>/", BookReviewDetailAPIView.as_view(), name="review-detail"),
]

books/urls.py
from django.urls import path
from .views import BooglistView, Bookdetail, AddReviewView, EditReviewView, ConfirmDeleteReviewView, DeleteReviewView

app_name = 'books'
urlpatterns = [
    path('', BooglistView.as_view(), name='list'),
    path('<int:id>/', Bookdetail.as_view(), name="book_detail"),
    path('<int:id>/reviews/', AddReviewView.as_view(), name='reviews'),
    path('<int:book_id>/reviews/<int:review_id>/edit/', EditReviewView.as_view(), name="edit-review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/confirm/", ConfirmDeleteReviewView.as_view(), name='confirm-delete-review'),
    path("<int:book_id>/reviews/<int:review_id>/delete/", DeleteReviewView.as_view(), name='delete-review')

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, Review_listView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('home/', Review_listView.as_view(), name='home_review'),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('books/', include('books.urls')),
    
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone

from users.models import CustomUser

class Book(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    cover_picture = models.ImageField(upload_to='book_image/', null=True, blank=True, default='book_image/default_book.png')

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def full_name(self):
        return f"{self.first_name} {self.last_name}"


class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.book.title} by avtor {self.author.first_name} {self.author.last_name}"


class BookReview(models.Model):
    objects = None
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    stars_given = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateTimeField(default=timezone.now)

books/forms.py
from django import forms
from books.models import BookReview
class BookReviewForm(forms.ModelForm):
    stars_given = forms.IntegerField(min_value=1, max_value=5)
    class Meta:
        model = BookReview
        fields = ('stars_given', 'comment')

books/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from .forms import BookReviewForm
from .models import Book, BookReview
# Create your views here.

class BooglistView(View):
    def get(self,request):
        books = Book.objects.all().order_by('id')
        search_query = request.GET.get('q', '')
        if search_query:
            books = books.filter(title__icontains=search_query)
        page_size = request.GET.get('page_size', 4)
        paginator = Paginator(books, page_size)

        page_num = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_num)
        return render(request, 'book/list.html', {"page_obj":page_obj, 'search_query':search_query})


class Bookdetail(LoginRequiredMixin,View):
    def get(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm()
        return render(request, 'book/book_detail.html', {"book": book, 'review_form': review_form})


class AddReviewView(View):
    def post(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm(request.POST)

        if review_form.is_valid():
            BookReview.objects.create(
                book = book,
                user = request.user,
                stars_given = review_form.cleaned_data['stars_given'],
                comment = review_form.cleaned_data['comment']
            )

            return redirect(reverse('books:book_detail', kwargs={"id":book.id}))

        return render(request, 'books/book_detail.html', {"book":book, "review_form":review_form})


class EditReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewForm(instance=review)

        return render(request,"book/edit_review.html", {"book":book, "review":review, 'review_form':review_form})

    def post(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewForm(instance=review, data=request.POST)

        if review_form.is_valid():
            review_form.save()
            return redirect(reverse('books:book_detail', kwargs={"id": book.id}))

        return render(request, "book/edit_review.html", {"book": book, "review": review, 'review_form': review_form})


class ConfirmDeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)

        return render(request, "book/confirm_delete_review.html", {"book": book, "review": review})


class DeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)

        review.delete()
        messages.success(request, "You have successfully deleted this review")

        return redirect(reverse('books:book_detail', kwargs={"id": book.id}))

templates/book/book_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        <div class="col-2">
            <img src="{{ book.cover_picture.url }}" alt="cover image" class="cover-pic">
        </div>

        <div class="col-6 ms-4">
            <h3>{{book.title}}</h3>

            <span class="fst-italic">
                Author by
                {% for book_author in book.bookauthor_set.all %}
                    {% if forloop.last %}
                    {{book_author.author.full_name}}
                    {% else %}
                    {{book_author.author.full_name}},
                    {% endif %}
                {% endfor %}
            </span>
            <p>
                {{book.description}}
            </p>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-6">
            <form method="post" action="{% url 'books:reviews' book.id %}">
                {% csrf_token %}
                {{ review_form | crispy }}
                <button type="submit" class="btn btn-success">Add review</button>
            </form>
        </div>
    </div>


    {% if book.bookreview_set.exists %}
    <h4>Reviews</h4>
    <hr>
    {% for review in book.bookreview_set.all %}
        <div class="row mb-3">
            <div class="col-1">
                <img class="small-profile-pic" src="{{ review.user.profile_pictures.url }}">
            </div>
            <div class="col-7">
                <b>{{review.user.username}}</b> rated it {{review.stars_given}} stars <span class="fw-lighter">{{review.created_at}}</span>
                {% if review.user.username == user.username %}
                <a href="{% url 'books:edit-review' book.id review.id %}"><i class="bi bi-pen"></i></a>
                <a href="{% url 'books:confirm-delete-review' book.id review.id %}"><i class="bi bi-trash"></i></a>
                {% endif %}
                <p class="mt-2 font-monospace">
                    {{review.comment}}
                </p>
            </div>
        </div>
        {% endfor %}
    {% endif %}




{% endblock%}

templates/book/confirm_delete_review.html
{% extends 'base.html' %}

{% block content %}
    <h3>Are you sure you want to delete this review</h3>

    <p>
        <b>Book</b>: {{book.title}}
    </p>

    <p>
        <b>Comment</b>: {{review.comment}}
    </p>

    <a href="{% url 'books:delete-review' book.id review.id %}" class="btn btn-outline-danger">Yes</a> <a href="{% url 'books:book_detail' book.id %} " class="btn btn-outline-primary">No</a>
{% endblock %}

templates/book/edit_review.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h3>Edit</h3>

    <div class="row mb-4">
        <div class="col-6">
            <form method="post" action="{% url 'books:edit-review' book.id review.id %}">
                {% csrf_token %}
                {{ review_form | crispy }}
                <button type="submit" class="btn btn-success">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/book/list.html
{% extends "base.html" %}

{% block content %}

    <h1>Books</h1>

    <div class="row mb-3">
        <div class="col-4">
            <form method="get" class="d-flex">
                <input type="text" placeholder="Search" class="form-control me-2" name="q" value="{{search_query}}">
                <button class="btn btn-success">Search</button>
            </form>

        </div>

    </div>
    {% if page_obj %}
        {% for book in page_obj.object_list %}
            <div class="row mb-4">
               <div class="col-2">
                   <img src="{{ book.cover_picture.url }}" alt="book image" class="cover-pic">
               </div>
               <div class="col-6 ms-4">
                    <a href="{% url 'books:book_detail' book.id %}">{{book.title}}</a>
                   <p>
                       {{book.description}}
                   </p>
               </div>
            </div>

        {% endfor %}

        <nav aria-label="...">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1" >first</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number}}">{{ page_obj.previous_page_number }}</a></li>
                {% endif %}

                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{page_obj.number}}</a>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number}}">{{ page_obj.next_page_number}}</a></li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Next</a>
                    </li>
                {% endif %}
          </ul>
        </nav>
    {% else %}
        No books found.
    {% endif %}

{% endblock %}