api/urls.py
from django.urls import path

from api.views import BookReviewDetailAPIView, BookReviewAPIView

app_name = 'api'
urlpatterns = [
    path("reviews/", BookReviewAPIView.as_view(), name='review-list'),
    path("reviews/<int:id>/", BookReviewDetailAPIView.as_view(), name="review-detail"),
]

books/urls.py
from django.urls import path
from .views import BooglistView, Bookdetail, AddReviewView, EditReviewView, ConfirmDeleteReviewView, DeleteReviewView

app_name = 'books'
urlpatterns = [
    path('', BooglistView.as_view(), name='list'),
    path('<int:id>/', Bookdetail.as_view(), name="book_detail"),
    path('<int:id>/reviews/', AddReviewView.as_view(), name='reviews'),
    path('<int:book_id>/reviews/<int:review_id>/edit/', EditReviewView.as_view(), name="edit-review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/confirm/", ConfirmDeleteReviewView.as_view(), name='confirm-delete-review'),
    path("<int:book_id>/reviews/<int:review_id>/delete/", DeleteReviewView.as_view(), name='delete-review')

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, Review_listView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('home/', Review_listView.as_view(), name='home_review'),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('books/', include('books.urls')),
    
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("profile/", ProfileView.as_view(), name='profile'),
    path("profile-edit/", ProfileUpdateView.as_view(), name="profile_edit")
]

templates/base.html
{% load static %}
{% url 'home_review' as home_review_url %}
{% url 'books:list' as book_list_url %}
{% url 'users:profile' as users_profile_url %}
{% url 'users:profile_edit' as users_profile_edit_url %}

<!DOCTYPE html>



<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}Goodreads Clone{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <link rel="stylesheet" href="{% static 'css/users.css' %}" type="text/css">
</head>
<body class="mx-5">
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-4 bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Goodreads clone</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.path == home_review_url %} active {% endif %}" href="{{home_review_url}}">Home Review</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == book_list_url  %} active {% endif %}" href="{{book_list_url }}">Book list</a>
        </li>

      </ul>
      <div class="me-5">
          {% if request.user.is_authenticated %}
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle {% if request.path == users_profile_url or request.path == users_profile_edit_url %} active {% endif %}" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ request.user.username}}
            </a>
                <ul class="dropdown-menu">
                  <li> <a href="{{users_profile_url}}" class="dropdown-item">Profile</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                </ul>
            </li>
          </ul>
          {% else %}
          <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
          {% endif %}
      </div>
    </div>
  </div>
</nav>
<div class="container">
    {% if messages %}

        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}

    {% endif %}

    {% block content %}

    {% endblock %}
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
    <h1>Home Page</h1>
    {% if messages %}
        {% for message in messages %}
            <span class="{{ message.tags }}">{{ message }}</span>
        {% endfor %}
    {% endif %}
    <p>
        Goodreads is an American social cataloging website and a subsidiary of Amazon[1] that allows individuals to search its database of books, annotations, quotes, and reviews. CustomUsers can sign up and register books to generate library catalogs and reading lists.
        They can also create their own groups of book suggestions, surveys, polls, blogs, and discussions.
        The website's offices are located in San Francisco.[2]
        Goodreads was founded in December 2006 and launched in January 2007 by Otis Chandler and Elizabeth Khuri Chandler.[3][4] In December 2007, the site had 650,000 members[5] and 10,000,000 books had been added.[6] By July 2012, the site reported 10 million members, 20 million monthly visits, and thirty employees.[7] On March 28, 2013, Amazon announced its acquisition of Goodreads,[8] and by July 23, 2013, Goodreads announced their CustomUser base had grown to 20 million members.[9]
    </p>
{% endblock %}

templates/review_list.html
{% extends "base.html" %}

{% block content %}
    <h1>All reviews</h1>
    {% for review in page_obj %}
       <div class="container posts-content">
        <div class="row">
            <div class="col-lg-6">
                <div class="card mb-4">
                  <div class="card-body">
                    <div class="media mb-3">
                      <img src="{{ review.user.profile_pictures.url }}" class="d-block ui-w-40 rounded-circle" alt="">
                      <div class="media-body ml-3">
                          <b>{{review.user.username}}</b> rated this book {{review.stars_given}} stars
                        <div class="text-muted small">{{review.created_at | date:"M d, Y"}}</div>
                      </div>
                    </div>

                    <p>
                     {{review.comment | truncatewords:20}}
                    </p>
                      <img src="{{ review.book.cover_picture.url }}" class="cover-pic center">
                  </div>
                </div>
            </div>

        </div>
    </div>
    {% endfor %}

    <nav aria-label="...">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1" >first</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number}}">{{ page_obj.previous_page_number }}</a></li>
                {% endif %}

                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{page_obj.number}}</a>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number}}">{{ page_obj.next_page_number}}</a></li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Next</a>
                    </li>
                {% endif %}
          </ul>
        </nav>
{% endblock %}