api/urls.py
from django.urls import path

from api.views import BookReviewDetailAPIView, BookReviewAPIView

app_name = 'api'
urlpatterns = [
    path("reviews/", BookReviewAPIView.as_view(), name='review-list'),
    path("reviews/<int:id>/", BookReviewDetailAPIView.as_view(), name="review-detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, Review_listView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('home/', Review_listView.as_view(), name='home_review'),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('books/', include('books.urls')),
    
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("profile/", ProfileView.as_view(), name='profile'),
    path("profile-edit/", ProfileUpdateView.as_view(), name="profile_edit")
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class CustomUser(AbstractUser):
    profile_pictures = models.ImageField(upload_to='users_profile/', null=True, blank=True, default='users_profile/default-profile-pic.png')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

users/forms.py
from django import forms


from users.models import CustomUser

class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', "first_name", 'last_name', 'email', 'password', 'profile_pictures')

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()

        return user


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', "first_name", 'last_name', 'email', 'profile_pictures')

users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from users.forms import UserCreateForm, ProfileUpdateForm


class RegisterView(View):
    @staticmethod
    def get(request):
        create_form = UserCreateForm()
        context = {
            "form": create_form
        }
        return render(request, 'users/register.html', context)

    @staticmethod
    def post(request):
        create_form = UserCreateForm(data=request.POST)

        if create_form.is_valid():
            create_form.save()
            return redirect('users:login')
        else:
            context = {
                "form": create_form
            }
            return render(request, 'users/register.html', context)


class LoginView(View):
    @staticmethod
    def get(request):
        login_form = AuthenticationForm()
        return render(request, 'users/login.html', {"login_form": login_form})

    @staticmethod
    def post(request):
        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, "You have successfully logged in")
            return redirect("books:list")
        else:
            return render(request, 'users/login.html', {"login_form": login_form})


class ProfileView(LoginRequiredMixin, View):
    @staticmethod
    def get(request):
        user = request.user
        return render(request, 'users/profile.html', {"user": user})


class ProfileUpdateView(LoginRequiredMixin, View):
    @staticmethod
    def get(request):
        user_profile_form = ProfileUpdateForm(instance=request.user)
        return render(request, 'users/profile_edit.html', {"form": user_profile_form})

    @staticmethod
    def post(request):
        user_profile_form = ProfileUpdateForm(
            instance=request.user,
            data=request.POST,
            files=request.FILES
        )
        if user_profile_form.is_valid():
            user_profile_form.save()
            messages.success(request, "You have successfully updated your profile.")

            return redirect("users:profile")

        return render(request, 'users/profile_edit.html', {"form": user_profile_form})

class LogoutView(LoginRequiredMixin, View):
    @staticmethod
    def get(request):
        logout(request)
        messages.info(request, "You have successfully logged out.")
        return redirect('home')

templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

    <h1>Login Page</h1>
    <div class="row">
        <div class="col-4">
            <form method="post" action="{% url 'users:login' %}">
                {% csrf_token %}
                {{ login_form|crispy }}

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>

    <p>No account:<a href="{% url 'users:register' %}">Register</a></p>

{% endblock %}

templates/users/profile.html
{% extends "base.html" %}

{% block content %}

        <div class=" image d-flex flex-column justify-content-center align-items-center">
            <button class="btn btn-secondary">
                <img src="{{ user.profile_pictures.url }}" height="100" width="100" class="profile-pic"/>
            </button>

            <span class="name mt-3">{{user.first_name}} {{user.last_name}}</span>
            <span class="idd">@{{ user.username }}</span>
            <span class="idd">{{ user.email }}</span>
            <div class=" d-flex mt-2"><a href="{% url 'users:profile_edit' %}">
                <button class="btn1 btn-dark">Edit Profile</button></a>
            </div>

            <div class=" px-2 rounded mt-4 date "> <span class="join">{{user.date_joined|date:"M d, Y"}}</span>
            </div>
        </div>

{% endblock%}

templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Profile Update</h1>
    <div class="row">
        <div class="col-4">
            <form action="{% url 'users:profile_edit' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">save edit</button>
             </form>
        </div>
    </div>


{% endblock %}

templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Register Page</h1>

<div class="row">
    <div class="col-6">
         <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}

        {{ form|crispy }}

        <button type="submit" class="btn btn-primary">Submit</button>
</form>
    </div>

</div>


{% endblock %}